[package]
name = "lang-parsing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
std = ["lang-lexing/std"]

[dependencies]
lang-lexing = { path = "../lang-lexing", features = ["alloc"] }
